spring:
  application:
    name: prove
  datasource:
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  springdoc:
    api-docs:
      enabled: true
      path: /openapi.json
    swagger-ui:
      enabled: true
      path: /swagger-ui.html

cors:
  allowed-origins:
    - "http://localhost:5173"
    - "https://prove-vue.tagitech.com"
    - "https://*.tagitech.com"  # Wildcard. tagitech is trusted domain.
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers:
    - "*"
  allow-credentials: true
  max-age: 3600

